### ISSUE TITLE
XYZ tiles give HTTP error 504

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-sentinelhub-python-driver#1]
For the XYZ tiles, I get a HTTP  error 504 for each tile I'm requesting via Editor. I am using your example web service process graph from the README over Germany.

Example: https://e3oind87n9.execute-api.eu-central-1.amazonaws.com/production/service/xyz/d243d92c-4cb3-4de6-a879-2c849fe9477e/7/67/44

**Comment by sinergise-anze** [comment]
Thank you for the bug report! Currently the system has issues when the request is too big, meaning:
- over a large area (== when zoomed out), 
- long timespan or
- uses all of the bands.

Responses are unfortunately limited to about 30 seconds (can't change it on this infrastructure, it is a limitation of CloudFront) and we haven't dealt properly with scalability yet (though we do have some ideas on how to proceed in this way too).

For now, it helps if you zoom in, select just a few days and only the bands that are need (and maybe wait a while if the system is overwhelmed with old requests :-/ ). Hope it helps.

**Comment by dthiex** [comment]
Closing as this shouldn't be an issue anymore (we removed the 30s timeout with our last bigger updated).
