### ISSUE TITLE
move development and deploy fully to github

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-sentinelhub-python-driver#23]
As most funding we get for this requires the backend to be open source and the whole openEO community (all other repos) are on github it will be easier and make sense to move the development their.

old internal issue: https://git.sinergise.com/team-6/openeo-platform/-/issues/234

**Comment by zcernigoj** [comment]
The usual git repository setup is such that you have 1 remote repository set - named `origin` - most noticeable when you push the branch (`git push origin name-of-branch`) or pull the changes from the remote repository (`git pull origin name-of-branch`).

The term "remote repository" here is not in a sense that something is physically added to the repository (or removed, if you remove the remote repository), it's just a pair of some name and URL which you can then use to push changes to or pull changes from.

To list the remote repositories that are set up in your git repository, execute `git remote -v` (`-v` flag to print the URLs of the remote repositories).

To add an additional remote repository, execute `git remote add your-name-for-this-remote-repo https://github.com/Open-EO/openeo-sentinelhub-python-driver.git`

To remove the existing remote repository, execute `git remote remove name-of-existing-remote-repo`

To change the URL of the existing remote repo, execute `git remote set-url name-of-remote-repo new-url`

To rename an existing remote repo, execute `git remote rename previous-name new-name`


More in https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories

My setup

```bash
$ git remote -v
github  https://github.com/Open-EO/openeo-sentinelhub-python-driver.git (fetch)
github  https://github.com/Open-EO/openeo-sentinelhub-python-driver.git (push)
origin  ... (fetch)
origin  ... (push)
```

---


Another option is also to (locally, on your computer) delete the existing repository (which is probably cloned from gitlab) and clone the github one.
