### ISSUE TITLE
Rate limiting for all deployments

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-sentinelhub-python-driver#25]
EU central (and perhaps also Creodias) should now support the new version of rate limiting. Currently it's only used for US west.

One of the first steps here will be to check what we did on US west and check with core if a switch to the new rate limiting is desired.

**Comment by zansinergise** [comment]
Talked with Eva, Jan and Rok Močnik and got confirmation that rate limiting is supported on all three deployments where all three deployments append the `retry-after` header to the responses (which is all we need I believe) - so we should be good to go to support it everywhere
