### ISSUE TITLE
properties eo:bands, array is nested one level too deep

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-sentinelhub-python-driver#3]
It seems that your "eo:bands" is nested one level too deep, which causes the openeo-python-client to fail retrieving band metadata information.
This is for openEO v0.4 and STAC 0.6

Example from [https://e3oind87n9.execute-api.eu-central-1.amazonaws.com/production/collections/S2L1C](https://e3oind87n9.execute-api.eu-central-1.amazonaws.com/production/collections/S2L1C)

```
"properties": {
    "eo:bands": [
      [
        {
          "center_wavelength": 4.439,
          "common_name": "coastal",
          "gsd": 60,
          "name": "B01"
        },
...
]]
}
```

Example from [https://earthengine.openeo.org/v0.4/collections/COPERNICUS/S2](https://earthengine.openeo.org/v0.4/collections/COPERNICUS/S2)
```
"properties": {
    "eo:bands": [
      {
        "name": "B1",
        "description": "Aerosols",
        "center_wavelength": 0.4439,
        "gsd": 60,
        "gee:scale": 0.0001,
        "gee:wavelength": "443.9nm (S2A) / 442.3nm (S2B)"
      },
...
]
}
```

**Comment by lforesta** [comment]
Also, cube:dimensions is missing from the endpoint. The python client looks for this information under "cube:dimensions" (STAC 0.9) or "properties/cube:dimensions" (STAC 0.6), else defaults to "spectral_bands" and "temporal" for these two common dimensions, which does not fit your back-end I think.

[https://github.com/Open-EO/openeo-python-client/issues/116#issuecomment-627238963](https://github.com/Open-EO/openeo-python-client/issues/116#issuecomment-627238963)

**Comment by mkadunc** [comment]
Has been fixed today.
