### ISSUE TITLE
/file_formats title and description

### ISSUE THREAD

**Issue by guss84** [Open-EO/openeo-sentinelhub-python-driver#58]
`GET /file_formats` lists all supported file formats, but title and description is missing for each format. We can copy this from Cito if the format is supported, https://openeocloud.vito.be/openeo/1.2/file_formats

**Comment by zcernigoj** [comment]
In the `output` part of Vito response (listed the formats in which the backend can return the data)
- `jpeg`, `zarr` have no title, description (same as ours)
- `gtiff`, `png`, `netcdf` have description and title
